//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Жанр { get; set; }
        public string Автор { get; set; }
        public string Цена { get; set; }
        public string Кол_во_в_магазине { get; set; }
        public string Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Обложка { get; set; }
    }
}
